module.exports = [
    {value : 'fineDining', label : 'Fine Dining'},
    {value : 'casualDining', label : 'Casual Dining'},
    {value : 'fastFood', label : 'Fast Food'},
    {value : 'cafe', label : 'Cafe'},
    {value : 'buffet', label : 'Buffet'},
    {value : 'foodTruck', label : 'Food Truck'},
    {value : 'familyStyle', label : 'Family Style'},
    {value : 'ethnic', label : 'Ethnic'},
    {value : 'vegetarian', label : 'Vegetarian'},
    {value : 'seaFood', label : 'Sea Food'},
    {value : 'steakHouse', label : 'Steak House'},
    {value : 'pizzeria', label : 'Pizzeria'},
    {value : 'bistro', label : 'Bistro'},
    {value : 'brasserie', label : 'Brasserie'},
    {value : 'sushi', label : 'Sushi'},
    {value : 'izakaya', label : 'Izakaya'},
    {value : 'tapasBar', label : 'Tapas Bar'},
    {value : 'barbecue', label : 'Barbecue'},
    {value : 'diner', label : 'Diner'},
    {value : 'driveThru', label : 'Drive-Thru'},
    {value : 'hotelRestaurant', label : 'Hotel Restaurant'},
    {value : 'pubBarCafe', label : 'Pub, Bar & Cafe'},
    {value : 'dhaba', label : 'Dhaba'},
    {value : 'bakery', label : 'Bakery'},
    {value : 'iceCreamParlor', label : 'Ice Cream Parlor'},
    {value : 'teahouse', label : 'Teahouse'},
    {value : 'streetFood', label : 'Street food'},
    {value : 'bar', label : 'Bar'},
    {value : 'pub', label : 'Pub'},
    {value : 'cafe', label : 'Cafe'},
    {value : 'foodCourt', label : 'Food Court'},
]