export default [
    {value : "northIndian", label : "North Indian"},
    {value : "southIndian", label : "South Indian"},
    {value : "punjabi", label : "Punjabi"},
    {value : "gujarati", label : "Gujarati"},
    {value : "rajasthani", label : "Rajasthani"},
    {value : "maharashtrian", label : "Maharashtrian"},
    {value : "bengali", label : "Bengali"},
    {value : "kashmiri", label : "Kashmiri"},
    {value : "hyderabadi", label : "Hyderabadi"},
    {value : "mughlai", label : "Mughlai"},
    {value : "awadhi", label : "Awadhi"},
    {value : "goan", label : "Goan"},
    {value : "chettinad", label : "Chettinad"},
    {value : "kerala", label : "Kerala"},
    {value : "andhra", label : "Kerala"},
    {value : "sindhi", label : "Sindhi"},
    {value : "assamese", label : "Assamese"},
    {value : "oriya", label : "Oriya"},
    {value : "manipuri", label : "Manipuri"},
    {value : "naga", label : "Naga"},
    {value : "italian", label : "Italian"},
    {value : "mexican", label : "Mexican"},
    {value : "chinese", label : "Chinese"},
    {value : "indian", label : "Indian"},
    {value : "japanese", label : "Japanese"},
    {value : "thai", label : "Thai"},
    {value : "french", label : "French"},
    {value : "spanish", label : "Spanish"},
    {value : "greek", label : "Greek"},
    {value : "korean", label : "Korean"},
    {value : "turkish", label : "Turkish"},
    {value : "lebanese", label : "Lebanese"},
    {value : "vietnamese", label : "Vietnamese"},
    {value : "american", label : "American"},
    {value : "british", label : "British"},
    {value : "brazilian", label : "Brazilian"},
    {value : "moroccan", label : "Moroccan"},
    {value : "ethiopia", label : "Ethiopian"},
    {value : "peruvian", label : "Peruvian"},
    {value : "russian", label : "Russian"},
    {value : "tea", label : "Tea"},
    {value : "biryani", label : "Biryani"},
    {value : "dessert", label : "Dessert"},
    {value : "iceCream", label : "Ice-Cream"},
    {value : "pizza", label : "Pizza"},
    {value : "chaat", label : "Chaat"},
    {value : "chaap", label : "Chaap"},
    {value : "tandoor", label : "Tandoor"},
    {value : "breakfast", label : "Breakfast"},
    {value : "beverages", label : "Beverages"},
    {value : "littiChokha", label : "Litti Choka"},
]