export default [
    {value : "airConditioned", label : "Air Conditioned"},
    {value : "candleLightDinner", label : "Candle Light Dinner"},
    {value : "cardsAccepted", label : "Card Accepted"},
    {value : "dj", label : "DJ"},
    {value : "danceFloor", label : "Dance Floor"},
    {value : "differentlyAbledFriendly", label : "Differently Abled Friendly"},
    {value : "driveThrough", label : "Drive-Thru"},
    {value : "fullBarAvailable", label : "Full Bar Available"},
    {value : "homeDelivery", label : "Home Delivery"},
    {value : "hookah", label : "Hookah"},
    {value : "karaoke", label : "Karaoke"},
    {value : "lift", label : "Lift"},
    {value : "livePerformace", label : "Live Performance"},
    {value : "liveScreening", label : "Live Screening"},
    {value : "outdoorSeating", label : "Outdoor Seating"},
    {value : "parking", label : "Parking"},
    {value : "petFriendly", label : "Pet Friendly"},
    {value : "poolSide", label : "Pool Side"},
    {value : "privateDiningAvailable", label : "Private Dining Available"},
    {value : "roofTop", label : "Roof Top"},
    {value : "servesAlcohol", label : "Serves Alcohol"},
    {value : "smokingArea", label : "Smoking Area"},
    {value : "valetAvailable", label : "Valet Available"},
    {value : "walletAccepted", label : "Wallet Accepted"},
    {value : "wifi", label : "Wifi"},
    {value : "onlineOrdering", label : "Online Ordering"},
    {value : "reservationSystem", label : "Reservation System"},
    {value : "Takeaway", label : "Takeaway"},
    {value : "deliveryServices", label : "Delivery Services"},
]